project:
  type: book
  execute-dir: project
  output-dir: docs
  
execute:
  freeze: false

book:
  title: "Introduction to R for SAS programmers"
  author: "Sadchla Mascary, Stefan Thoma,\n Zelos Zhu, Thomas Neitman"
  favicon: favicon-32x32.png
  date: today
  date-format: short
  chapters:
    - index.qmd   
    - part: "datatype & structure"
      chapters: 
        - datatype_structure.qmd
        - datatype_structure_exercise.qmd 
    - part: "dplyr"
      chapters: 
        - dplyr.qmd
        - dplyr_exercises.qmd
    - part: "mutate"
      chapters: 
        - mutate.qmd
        - mutate_exercises.qmd
    - part: "tidyr"
      chapters: 
        - tidyr.qmd
        - tidyr_exercises.qmd
  downloads: pdf
  
format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt
editor: visual

